### ISSUE TITLE
请问这个项目的原始项目是什么呢

### ISSUE THREAD

**Issue by liminghangsss** [Weiwei-Ch/image-tagger#1]
有原始项目链接吗，谢谢

**Comment by Weiwei-Ch** [comment]
这个是我上的付费课程里的一个项目，自己写的，没有原始项目代码。这个项目好像还挺出名的，你可以去github搜一下，看能找到其他的参考代码不。

**Comment by liminghangsss** [comment]
这几个pynb也是自己写的吗，像是教程一样，请问项目名或者课程名叫什么

> 这个是我上的付费课程里的一个项目，自己写的，没有原始项目代码。这个项目好像还挺出名的，你可以去github搜一下，看能找到其他的参考代码不。
> […](#)
> 在 2021年4月20日，上午11:20，liminghangsss ***@***.***> 写道： ﻿ 有原始项目链接吗，谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Weiwei-Ch** [comment]
是的，这就是课程教程，部分代码是项目自带的。课程是优达学城的AI算法工程师。这是我前年做的，也不知道现在有没有变。你要是感兴趣，可以去关注一下优达学城。课程还可以。

**Comment by liminghangsss** [comment]
> 是的，这就是课程教程，部分代码是项目自带的。课程是优达学城的AI算法工程师。这是我前年做的，也不知道现在有没有变。你要是感兴趣，可以去关注一下优达学城。课程还可以。
> […](#)
> 在 2021年4月20日，下午9:57，liminghangsss ***@***.***> 写道： ﻿ 这几个pynb也是自己写的吗，像是教程一样，请问项目名或者课程名叫什么 这个是我上的付费课程里的一个项目，自己写的，没有原始项目代码。这个项目好像还挺出名的，你可以去github搜一下，看能找到其他的参考代码不。 … 在 2021年4月20日，上午11:20，liminghangsss @.***> 写道： ﻿ 有原始项目链接吗，谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

了解了，谢谢，通过搜文件名找添加记录找到了很多关于这个的项目，去看看这个课程
